/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PresentationsRouteRouteImport } from './routes/presentations/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PresentationsIndexRouteImport } from './routes/presentations/index'
import { Route as PitchIndexRouteImport } from './routes/pitch/index'
import { Route as JudgingIndexRouteImport } from './routes/judging/index'
import { Route as PresentationsValuePropRouteImport } from './routes/presentations/value-prop'
import { Route as PresentationsPitchRouteImport } from './routes/presentations/pitch'
import { Route as PresentationsMvpRouteImport } from './routes/presentations/mvp'
import { Route as PresentationsMetricsRouteImport } from './routes/presentations/metrics'
import { Route as PresentationsIcpRouteImport } from './routes/presentations/icp'
import { Route as PresentationsGtmRouteImport } from './routes/presentations/gtm'
import { Route as JudgingValueRouteImport } from './routes/judging/value'
import { Route as JudgingMvpRouteImport } from './routes/judging/mvp'
import { Route as JudgingMetricsRouteImport } from './routes/judging/metrics'
import { Route as JudgingIcpRouteImport } from './routes/judging/icp'
import { Route as JudgingGtmRouteImport } from './routes/judging/gtm'
import { Route as AppDashboardIndexRouteImport } from './routes/_app/dashboard/index'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc/$'
import { Route as ApiNexusAuthSplatRouteImport } from './routes/api/nexus-auth/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppDashboardSuggestionsRouteImport } from './routes/_app/dashboard/suggestions'
import { Route as AppDashboardPolicyRouteImport } from './routes/_app/dashboard/policy'
import { Route as AppDashboardMarginCallsRouteImport } from './routes/_app/dashboard/margin-calls'
import { Route as AppDashboardHoldingsRouteImport } from './routes/_app/dashboard/holdings'
import { Route as AppDashboardGenerateRouteImport } from './routes/_app/dashboard/generate'
import { Route as AppDashboardComponents_libRouteImport } from './routes/_app/dashboard/components_lib'
import { Route as AppDashboardAuditRouteImport } from './routes/_app/dashboard/audit'
import { Route as AppDashboardUsersIndexRouteImport } from './routes/_app/dashboard/users/index'
import { Route as AppDashboardSettingsIndexRouteImport } from './routes/_app/dashboard/settings/index'
import { Route as AppDashboardUsersSettingsRouteImport } from './routes/_app/dashboard/users/settings'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationsRouteRoute = PresentationsRouteRouteImport.update({
  id: '/presentations',
  path: '/presentations',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationsIndexRoute = PresentationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PresentationsRouteRoute,
} as any)
const PitchIndexRoute = PitchIndexRouteImport.update({
  id: '/pitch/',
  path: '/pitch/',
  getParentRoute: () => rootRouteImport,
} as any)
const JudgingIndexRoute = JudgingIndexRouteImport.update({
  id: '/judging/',
  path: '/judging/',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationsValuePropRoute = PresentationsValuePropRouteImport.update({
  id: '/value-prop',
  path: '/value-prop',
  getParentRoute: () => PresentationsRouteRoute,
} as any)
const PresentationsPitchRoute = PresentationsPitchRouteImport.update({
  id: '/pitch',
  path: '/pitch',
  getParentRoute: () => PresentationsRouteRoute,
} as any)
const PresentationsMvpRoute = PresentationsMvpRouteImport.update({
  id: '/mvp',
  path: '/mvp',
  getParentRoute: () => PresentationsRouteRoute,
} as any)
const PresentationsMetricsRoute = PresentationsMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => PresentationsRouteRoute,
} as any)
const PresentationsIcpRoute = PresentationsIcpRouteImport.update({
  id: '/icp',
  path: '/icp',
  getParentRoute: () => PresentationsRouteRoute,
} as any)
const PresentationsGtmRoute = PresentationsGtmRouteImport.update({
  id: '/gtm',
  path: '/gtm',
  getParentRoute: () => PresentationsRouteRoute,
} as any)
const JudgingValueRoute = JudgingValueRouteImport.update({
  id: '/judging/value',
  path: '/judging/value',
  getParentRoute: () => rootRouteImport,
} as any)
const JudgingMvpRoute = JudgingMvpRouteImport.update({
  id: '/judging/mvp',
  path: '/judging/mvp',
  getParentRoute: () => rootRouteImport,
} as any)
const JudgingMetricsRoute = JudgingMetricsRouteImport.update({
  id: '/judging/metrics',
  path: '/judging/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const JudgingIcpRoute = JudgingIcpRouteImport.update({
  id: '/judging/icp',
  path: '/judging/icp',
  getParentRoute: () => rootRouteImport,
} as any)
const JudgingGtmRoute = JudgingGtmRouteImport.update({
  id: '/judging/gtm',
  path: '/judging/gtm',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNexusAuthSplatRoute = ApiNexusAuthSplatRouteImport.update({
  id: '/api/nexus-auth/$',
  path: '/api/nexus-auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardSuggestionsRoute = AppDashboardSuggestionsRouteImport.update({
  id: '/dashboard/suggestions',
  path: '/dashboard/suggestions',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardPolicyRoute = AppDashboardPolicyRouteImport.update({
  id: '/dashboard/policy',
  path: '/dashboard/policy',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardMarginCallsRoute = AppDashboardMarginCallsRouteImport.update({
  id: '/dashboard/margin-calls',
  path: '/dashboard/margin-calls',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardHoldingsRoute = AppDashboardHoldingsRouteImport.update({
  id: '/dashboard/holdings',
  path: '/dashboard/holdings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardGenerateRoute = AppDashboardGenerateRouteImport.update({
  id: '/dashboard/generate',
  path: '/dashboard/generate',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardComponents_libRoute =
  AppDashboardComponents_libRouteImport.update({
    id: '/dashboard/components_lib',
    path: '/dashboard/components_lib',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDashboardAuditRoute = AppDashboardAuditRouteImport.update({
  id: '/dashboard/audit',
  path: '/dashboard/audit',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardUsersIndexRoute = AppDashboardUsersIndexRouteImport.update({
  id: '/dashboard/users/',
  path: '/dashboard/users/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardSettingsIndexRoute =
  AppDashboardSettingsIndexRouteImport.update({
    id: '/dashboard/settings/',
    path: '/dashboard/settings/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDashboardUsersSettingsRoute =
  AppDashboardUsersSettingsRouteImport.update({
    id: '/dashboard/users/settings',
    path: '/dashboard/users/settings',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/presentations': typeof PresentationsRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/judging/gtm': typeof JudgingGtmRoute
  '/judging/icp': typeof JudgingIcpRoute
  '/judging/metrics': typeof JudgingMetricsRoute
  '/judging/mvp': typeof JudgingMvpRoute
  '/judging/value': typeof JudgingValueRoute
  '/presentations/gtm': typeof PresentationsGtmRoute
  '/presentations/icp': typeof PresentationsIcpRoute
  '/presentations/metrics': typeof PresentationsMetricsRoute
  '/presentations/mvp': typeof PresentationsMvpRoute
  '/presentations/pitch': typeof PresentationsPitchRoute
  '/presentations/value-prop': typeof PresentationsValuePropRoute
  '/judging/': typeof JudgingIndexRoute
  '/pitch/': typeof PitchIndexRoute
  '/presentations/': typeof PresentationsIndexRoute
  '/dashboard/audit': typeof AppDashboardAuditRoute
  '/dashboard/components_lib': typeof AppDashboardComponents_libRoute
  '/dashboard/generate': typeof AppDashboardGenerateRoute
  '/dashboard/holdings': typeof AppDashboardHoldingsRoute
  '/dashboard/margin-calls': typeof AppDashboardMarginCallsRoute
  '/dashboard/policy': typeof AppDashboardPolicyRoute
  '/dashboard/suggestions': typeof AppDashboardSuggestionsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/nexus-auth/$': typeof ApiNexusAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/dashboard/': typeof AppDashboardIndexRoute
  '/dashboard/users/settings': typeof AppDashboardUsersSettingsRoute
  '/dashboard/settings/': typeof AppDashboardSettingsIndexRoute
  '/dashboard/users/': typeof AppDashboardUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/judging/gtm': typeof JudgingGtmRoute
  '/judging/icp': typeof JudgingIcpRoute
  '/judging/metrics': typeof JudgingMetricsRoute
  '/judging/mvp': typeof JudgingMvpRoute
  '/judging/value': typeof JudgingValueRoute
  '/presentations/gtm': typeof PresentationsGtmRoute
  '/presentations/icp': typeof PresentationsIcpRoute
  '/presentations/metrics': typeof PresentationsMetricsRoute
  '/presentations/mvp': typeof PresentationsMvpRoute
  '/presentations/pitch': typeof PresentationsPitchRoute
  '/presentations/value-prop': typeof PresentationsValuePropRoute
  '/judging': typeof JudgingIndexRoute
  '/pitch': typeof PitchIndexRoute
  '/presentations': typeof PresentationsIndexRoute
  '/dashboard/audit': typeof AppDashboardAuditRoute
  '/dashboard/components_lib': typeof AppDashboardComponents_libRoute
  '/dashboard/generate': typeof AppDashboardGenerateRoute
  '/dashboard/holdings': typeof AppDashboardHoldingsRoute
  '/dashboard/margin-calls': typeof AppDashboardMarginCallsRoute
  '/dashboard/policy': typeof AppDashboardPolicyRoute
  '/dashboard/suggestions': typeof AppDashboardSuggestionsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/nexus-auth/$': typeof ApiNexusAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/dashboard/users/settings': typeof AppDashboardUsersSettingsRoute
  '/dashboard/settings': typeof AppDashboardSettingsIndexRoute
  '/dashboard/users': typeof AppDashboardUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/presentations': typeof PresentationsRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/judging/gtm': typeof JudgingGtmRoute
  '/judging/icp': typeof JudgingIcpRoute
  '/judging/metrics': typeof JudgingMetricsRoute
  '/judging/mvp': typeof JudgingMvpRoute
  '/judging/value': typeof JudgingValueRoute
  '/presentations/gtm': typeof PresentationsGtmRoute
  '/presentations/icp': typeof PresentationsIcpRoute
  '/presentations/metrics': typeof PresentationsMetricsRoute
  '/presentations/mvp': typeof PresentationsMvpRoute
  '/presentations/pitch': typeof PresentationsPitchRoute
  '/presentations/value-prop': typeof PresentationsValuePropRoute
  '/judging/': typeof JudgingIndexRoute
  '/pitch/': typeof PitchIndexRoute
  '/presentations/': typeof PresentationsIndexRoute
  '/_app/dashboard/audit': typeof AppDashboardAuditRoute
  '/_app/dashboard/components_lib': typeof AppDashboardComponents_libRoute
  '/_app/dashboard/generate': typeof AppDashboardGenerateRoute
  '/_app/dashboard/holdings': typeof AppDashboardHoldingsRoute
  '/_app/dashboard/margin-calls': typeof AppDashboardMarginCallsRoute
  '/_app/dashboard/policy': typeof AppDashboardPolicyRoute
  '/_app/dashboard/suggestions': typeof AppDashboardSuggestionsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/nexus-auth/$': typeof ApiNexusAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
  '/_app/dashboard/users/settings': typeof AppDashboardUsersSettingsRoute
  '/_app/dashboard/settings/': typeof AppDashboardSettingsIndexRoute
  '/_app/dashboard/users/': typeof AppDashboardUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/presentations'
    | '/login'
    | '/signup'
    | '/judging/gtm'
    | '/judging/icp'
    | '/judging/metrics'
    | '/judging/mvp'
    | '/judging/value'
    | '/presentations/gtm'
    | '/presentations/icp'
    | '/presentations/metrics'
    | '/presentations/mvp'
    | '/presentations/pitch'
    | '/presentations/value-prop'
    | '/judging/'
    | '/pitch/'
    | '/presentations/'
    | '/dashboard/audit'
    | '/dashboard/components_lib'
    | '/dashboard/generate'
    | '/dashboard/holdings'
    | '/dashboard/margin-calls'
    | '/dashboard/policy'
    | '/dashboard/suggestions'
    | '/api/auth/$'
    | '/api/nexus-auth/$'
    | '/api/rpc/$'
    | '/dashboard/'
    | '/dashboard/users/settings'
    | '/dashboard/settings/'
    | '/dashboard/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/judging/gtm'
    | '/judging/icp'
    | '/judging/metrics'
    | '/judging/mvp'
    | '/judging/value'
    | '/presentations/gtm'
    | '/presentations/icp'
    | '/presentations/metrics'
    | '/presentations/mvp'
    | '/presentations/pitch'
    | '/presentations/value-prop'
    | '/judging'
    | '/pitch'
    | '/presentations'
    | '/dashboard/audit'
    | '/dashboard/components_lib'
    | '/dashboard/generate'
    | '/dashboard/holdings'
    | '/dashboard/margin-calls'
    | '/dashboard/policy'
    | '/dashboard/suggestions'
    | '/api/auth/$'
    | '/api/nexus-auth/$'
    | '/api/rpc/$'
    | '/dashboard'
    | '/dashboard/users/settings'
    | '/dashboard/settings'
    | '/dashboard/users'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/presentations'
    | '/login'
    | '/signup'
    | '/judging/gtm'
    | '/judging/icp'
    | '/judging/metrics'
    | '/judging/mvp'
    | '/judging/value'
    | '/presentations/gtm'
    | '/presentations/icp'
    | '/presentations/metrics'
    | '/presentations/mvp'
    | '/presentations/pitch'
    | '/presentations/value-prop'
    | '/judging/'
    | '/pitch/'
    | '/presentations/'
    | '/_app/dashboard/audit'
    | '/_app/dashboard/components_lib'
    | '/_app/dashboard/generate'
    | '/_app/dashboard/holdings'
    | '/_app/dashboard/margin-calls'
    | '/_app/dashboard/policy'
    | '/_app/dashboard/suggestions'
    | '/api/auth/$'
    | '/api/nexus-auth/$'
    | '/api/rpc/$'
    | '/_app/dashboard/'
    | '/_app/dashboard/users/settings'
    | '/_app/dashboard/settings/'
    | '/_app/dashboard/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  PresentationsRouteRoute: typeof PresentationsRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  JudgingGtmRoute: typeof JudgingGtmRoute
  JudgingIcpRoute: typeof JudgingIcpRoute
  JudgingMetricsRoute: typeof JudgingMetricsRoute
  JudgingMvpRoute: typeof JudgingMvpRoute
  JudgingValueRoute: typeof JudgingValueRoute
  JudgingIndexRoute: typeof JudgingIndexRoute
  PitchIndexRoute: typeof PitchIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiNexusAuthSplatRoute: typeof ApiNexusAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentations': {
      id: '/presentations'
      path: '/presentations'
      fullPath: '/presentations'
      preLoaderRoute: typeof PresentationsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentations/': {
      id: '/presentations/'
      path: '/'
      fullPath: '/presentations/'
      preLoaderRoute: typeof PresentationsIndexRouteImport
      parentRoute: typeof PresentationsRouteRoute
    }
    '/pitch/': {
      id: '/pitch/'
      path: '/pitch'
      fullPath: '/pitch/'
      preLoaderRoute: typeof PitchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/judging/': {
      id: '/judging/'
      path: '/judging'
      fullPath: '/judging/'
      preLoaderRoute: typeof JudgingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentations/value-prop': {
      id: '/presentations/value-prop'
      path: '/value-prop'
      fullPath: '/presentations/value-prop'
      preLoaderRoute: typeof PresentationsValuePropRouteImport
      parentRoute: typeof PresentationsRouteRoute
    }
    '/presentations/pitch': {
      id: '/presentations/pitch'
      path: '/pitch'
      fullPath: '/presentations/pitch'
      preLoaderRoute: typeof PresentationsPitchRouteImport
      parentRoute: typeof PresentationsRouteRoute
    }
    '/presentations/mvp': {
      id: '/presentations/mvp'
      path: '/mvp'
      fullPath: '/presentations/mvp'
      preLoaderRoute: typeof PresentationsMvpRouteImport
      parentRoute: typeof PresentationsRouteRoute
    }
    '/presentations/metrics': {
      id: '/presentations/metrics'
      path: '/metrics'
      fullPath: '/presentations/metrics'
      preLoaderRoute: typeof PresentationsMetricsRouteImport
      parentRoute: typeof PresentationsRouteRoute
    }
    '/presentations/icp': {
      id: '/presentations/icp'
      path: '/icp'
      fullPath: '/presentations/icp'
      preLoaderRoute: typeof PresentationsIcpRouteImport
      parentRoute: typeof PresentationsRouteRoute
    }
    '/presentations/gtm': {
      id: '/presentations/gtm'
      path: '/gtm'
      fullPath: '/presentations/gtm'
      preLoaderRoute: typeof PresentationsGtmRouteImport
      parentRoute: typeof PresentationsRouteRoute
    }
    '/judging/value': {
      id: '/judging/value'
      path: '/judging/value'
      fullPath: '/judging/value'
      preLoaderRoute: typeof JudgingValueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/judging/mvp': {
      id: '/judging/mvp'
      path: '/judging/mvp'
      fullPath: '/judging/mvp'
      preLoaderRoute: typeof JudgingMvpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/judging/metrics': {
      id: '/judging/metrics'
      path: '/judging/metrics'
      fullPath: '/judging/metrics'
      preLoaderRoute: typeof JudgingMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/judging/icp': {
      id: '/judging/icp'
      path: '/judging/icp'
      fullPath: '/judging/icp'
      preLoaderRoute: typeof JudgingIcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/judging/gtm': {
      id: '/judging/gtm'
      path: '/judging/gtm'
      fullPath: '/judging/gtm'
      preLoaderRoute: typeof JudgingGtmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nexus-auth/$': {
      id: '/api/nexus-auth/$'
      path: '/api/nexus-auth/$'
      fullPath: '/api/nexus-auth/$'
      preLoaderRoute: typeof ApiNexusAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard/suggestions': {
      id: '/_app/dashboard/suggestions'
      path: '/dashboard/suggestions'
      fullPath: '/dashboard/suggestions'
      preLoaderRoute: typeof AppDashboardSuggestionsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/policy': {
      id: '/_app/dashboard/policy'
      path: '/dashboard/policy'
      fullPath: '/dashboard/policy'
      preLoaderRoute: typeof AppDashboardPolicyRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/margin-calls': {
      id: '/_app/dashboard/margin-calls'
      path: '/dashboard/margin-calls'
      fullPath: '/dashboard/margin-calls'
      preLoaderRoute: typeof AppDashboardMarginCallsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/holdings': {
      id: '/_app/dashboard/holdings'
      path: '/dashboard/holdings'
      fullPath: '/dashboard/holdings'
      preLoaderRoute: typeof AppDashboardHoldingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/generate': {
      id: '/_app/dashboard/generate'
      path: '/dashboard/generate'
      fullPath: '/dashboard/generate'
      preLoaderRoute: typeof AppDashboardGenerateRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/components_lib': {
      id: '/_app/dashboard/components_lib'
      path: '/dashboard/components_lib'
      fullPath: '/dashboard/components_lib'
      preLoaderRoute: typeof AppDashboardComponents_libRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/audit': {
      id: '/_app/dashboard/audit'
      path: '/dashboard/audit'
      fullPath: '/dashboard/audit'
      preLoaderRoute: typeof AppDashboardAuditRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/users/': {
      id: '/_app/dashboard/users/'
      path: '/dashboard/users'
      fullPath: '/dashboard/users/'
      preLoaderRoute: typeof AppDashboardUsersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/settings/': {
      id: '/_app/dashboard/settings/'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof AppDashboardSettingsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/users/settings': {
      id: '/_app/dashboard/users/settings'
      path: '/dashboard/users/settings'
      fullPath: '/dashboard/users/settings'
      preLoaderRoute: typeof AppDashboardUsersSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppDashboardAuditRoute: typeof AppDashboardAuditRoute
  AppDashboardComponents_libRoute: typeof AppDashboardComponents_libRoute
  AppDashboardGenerateRoute: typeof AppDashboardGenerateRoute
  AppDashboardHoldingsRoute: typeof AppDashboardHoldingsRoute
  AppDashboardMarginCallsRoute: typeof AppDashboardMarginCallsRoute
  AppDashboardPolicyRoute: typeof AppDashboardPolicyRoute
  AppDashboardSuggestionsRoute: typeof AppDashboardSuggestionsRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppDashboardUsersSettingsRoute: typeof AppDashboardUsersSettingsRoute
  AppDashboardSettingsIndexRoute: typeof AppDashboardSettingsIndexRoute
  AppDashboardUsersIndexRoute: typeof AppDashboardUsersIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDashboardAuditRoute: AppDashboardAuditRoute,
  AppDashboardComponents_libRoute: AppDashboardComponents_libRoute,
  AppDashboardGenerateRoute: AppDashboardGenerateRoute,
  AppDashboardHoldingsRoute: AppDashboardHoldingsRoute,
  AppDashboardMarginCallsRoute: AppDashboardMarginCallsRoute,
  AppDashboardPolicyRoute: AppDashboardPolicyRoute,
  AppDashboardSuggestionsRoute: AppDashboardSuggestionsRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppDashboardUsersSettingsRoute: AppDashboardUsersSettingsRoute,
  AppDashboardSettingsIndexRoute: AppDashboardSettingsIndexRoute,
  AppDashboardUsersIndexRoute: AppDashboardUsersIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface PresentationsRouteRouteChildren {
  PresentationsGtmRoute: typeof PresentationsGtmRoute
  PresentationsIcpRoute: typeof PresentationsIcpRoute
  PresentationsMetricsRoute: typeof PresentationsMetricsRoute
  PresentationsMvpRoute: typeof PresentationsMvpRoute
  PresentationsPitchRoute: typeof PresentationsPitchRoute
  PresentationsValuePropRoute: typeof PresentationsValuePropRoute
  PresentationsIndexRoute: typeof PresentationsIndexRoute
}

const PresentationsRouteRouteChildren: PresentationsRouteRouteChildren = {
  PresentationsGtmRoute: PresentationsGtmRoute,
  PresentationsIcpRoute: PresentationsIcpRoute,
  PresentationsMetricsRoute: PresentationsMetricsRoute,
  PresentationsMvpRoute: PresentationsMvpRoute,
  PresentationsPitchRoute: PresentationsPitchRoute,
  PresentationsValuePropRoute: PresentationsValuePropRoute,
  PresentationsIndexRoute: PresentationsIndexRoute,
}

const PresentationsRouteRouteWithChildren =
  PresentationsRouteRoute._addFileChildren(PresentationsRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  PresentationsRouteRoute: PresentationsRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  JudgingGtmRoute: JudgingGtmRoute,
  JudgingIcpRoute: JudgingIcpRoute,
  JudgingMetricsRoute: JudgingMetricsRoute,
  JudgingMvpRoute: JudgingMvpRoute,
  JudgingValueRoute: JudgingValueRoute,
  JudgingIndexRoute: JudgingIndexRoute,
  PitchIndexRoute: PitchIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiNexusAuthSplatRoute: ApiNexusAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
