/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SandboxAuthRouteImport } from './routes/sandbox-auth'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppDashboardIndexRouteImport } from './routes/_app/dashboard/index'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc/$'
import { Route as ApiNexusAuthSplatRouteImport } from './routes/api/nexus-auth/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppDashboardSuggestionsRouteImport } from './routes/_app/dashboard/suggestions'
import { Route as AppDashboardPolicyRouteImport } from './routes/_app/dashboard/policy'
import { Route as AppDashboardHoldingsRouteImport } from './routes/_app/dashboard/holdings'
import { Route as AppDashboardGenerateRouteImport } from './routes/_app/dashboard/generate'
import { Route as AppDashboardComponents_libRouteImport } from './routes/_app/dashboard/components_lib'
import { Route as AppDashboardAuditRouteImport } from './routes/_app/dashboard/audit'
import { Route as AppDashboardUsersIndexRouteImport } from './routes/_app/dashboard/users/index'
import { Route as AppDashboardSettingsIndexRouteImport } from './routes/_app/dashboard/settings/index'
import { Route as AppDashboardUsersSettingsRouteImport } from './routes/_app/dashboard/users/settings'

const SandboxAuthRoute = SandboxAuthRouteImport.update({
  id: '/sandbox-auth',
  path: '/sandbox-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNexusAuthSplatRoute = ApiNexusAuthSplatRouteImport.update({
  id: '/api/nexus-auth/$',
  path: '/api/nexus-auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardSuggestionsRoute = AppDashboardSuggestionsRouteImport.update({
  id: '/dashboard/suggestions',
  path: '/dashboard/suggestions',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardPolicyRoute = AppDashboardPolicyRouteImport.update({
  id: '/dashboard/policy',
  path: '/dashboard/policy',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardHoldingsRoute = AppDashboardHoldingsRouteImport.update({
  id: '/dashboard/holdings',
  path: '/dashboard/holdings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardGenerateRoute = AppDashboardGenerateRouteImport.update({
  id: '/dashboard/generate',
  path: '/dashboard/generate',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardComponents_libRoute =
  AppDashboardComponents_libRouteImport.update({
    id: '/dashboard/components_lib',
    path: '/dashboard/components_lib',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDashboardAuditRoute = AppDashboardAuditRouteImport.update({
  id: '/dashboard/audit',
  path: '/dashboard/audit',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardUsersIndexRoute = AppDashboardUsersIndexRouteImport.update({
  id: '/dashboard/users/',
  path: '/dashboard/users/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardSettingsIndexRoute =
  AppDashboardSettingsIndexRouteImport.update({
    id: '/dashboard/settings/',
    path: '/dashboard/settings/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDashboardUsersSettingsRoute =
  AppDashboardUsersSettingsRouteImport.update({
    id: '/dashboard/users/settings',
    path: '/dashboard/users/settings',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sandbox-auth': typeof SandboxAuthRoute
  '/dashboard/audit': typeof AppDashboardAuditRoute
  '/dashboard/components_lib': typeof AppDashboardComponents_libRoute
  '/dashboard/generate': typeof AppDashboardGenerateRoute
  '/dashboard/holdings': typeof AppDashboardHoldingsRoute
  '/dashboard/policy': typeof AppDashboardPolicyRoute
  '/dashboard/suggestions': typeof AppDashboardSuggestionsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/nexus-auth/$': typeof ApiNexusAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/dashboard/': typeof AppDashboardIndexRoute
  '/dashboard/users/settings': typeof AppDashboardUsersSettingsRoute
  '/dashboard/settings/': typeof AppDashboardSettingsIndexRoute
  '/dashboard/users/': typeof AppDashboardUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sandbox-auth': typeof SandboxAuthRoute
  '/dashboard/audit': typeof AppDashboardAuditRoute
  '/dashboard/components_lib': typeof AppDashboardComponents_libRoute
  '/dashboard/generate': typeof AppDashboardGenerateRoute
  '/dashboard/holdings': typeof AppDashboardHoldingsRoute
  '/dashboard/policy': typeof AppDashboardPolicyRoute
  '/dashboard/suggestions': typeof AppDashboardSuggestionsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/nexus-auth/$': typeof ApiNexusAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/dashboard/users/settings': typeof AppDashboardUsersSettingsRoute
  '/dashboard/settings': typeof AppDashboardSettingsIndexRoute
  '/dashboard/users': typeof AppDashboardUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/sandbox-auth': typeof SandboxAuthRoute
  '/_app/dashboard/audit': typeof AppDashboardAuditRoute
  '/_app/dashboard/components_lib': typeof AppDashboardComponents_libRoute
  '/_app/dashboard/generate': typeof AppDashboardGenerateRoute
  '/_app/dashboard/holdings': typeof AppDashboardHoldingsRoute
  '/_app/dashboard/policy': typeof AppDashboardPolicyRoute
  '/_app/dashboard/suggestions': typeof AppDashboardSuggestionsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/nexus-auth/$': typeof ApiNexusAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
  '/_app/dashboard/users/settings': typeof AppDashboardUsersSettingsRoute
  '/_app/dashboard/settings/': typeof AppDashboardSettingsIndexRoute
  '/_app/dashboard/users/': typeof AppDashboardUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/sandbox-auth'
    | '/dashboard/audit'
    | '/dashboard/components_lib'
    | '/dashboard/generate'
    | '/dashboard/holdings'
    | '/dashboard/policy'
    | '/dashboard/suggestions'
    | '/api/auth/$'
    | '/api/nexus-auth/$'
    | '/api/rpc/$'
    | '/dashboard/'
    | '/dashboard/users/settings'
    | '/dashboard/settings/'
    | '/dashboard/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/sandbox-auth'
    | '/dashboard/audit'
    | '/dashboard/components_lib'
    | '/dashboard/generate'
    | '/dashboard/holdings'
    | '/dashboard/policy'
    | '/dashboard/suggestions'
    | '/api/auth/$'
    | '/api/nexus-auth/$'
    | '/api/rpc/$'
    | '/dashboard'
    | '/dashboard/users/settings'
    | '/dashboard/settings'
    | '/dashboard/users'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/sandbox-auth'
    | '/_app/dashboard/audit'
    | '/_app/dashboard/components_lib'
    | '/_app/dashboard/generate'
    | '/_app/dashboard/holdings'
    | '/_app/dashboard/policy'
    | '/_app/dashboard/suggestions'
    | '/api/auth/$'
    | '/api/nexus-auth/$'
    | '/api/rpc/$'
    | '/_app/dashboard/'
    | '/_app/dashboard/users/settings'
    | '/_app/dashboard/settings/'
    | '/_app/dashboard/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SandboxAuthRoute: typeof SandboxAuthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiNexusAuthSplatRoute: typeof ApiNexusAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sandbox-auth': {
      id: '/sandbox-auth'
      path: '/sandbox-auth'
      fullPath: '/sandbox-auth'
      preLoaderRoute: typeof SandboxAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nexus-auth/$': {
      id: '/api/nexus-auth/$'
      path: '/api/nexus-auth/$'
      fullPath: '/api/nexus-auth/$'
      preLoaderRoute: typeof ApiNexusAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard/suggestions': {
      id: '/_app/dashboard/suggestions'
      path: '/dashboard/suggestions'
      fullPath: '/dashboard/suggestions'
      preLoaderRoute: typeof AppDashboardSuggestionsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/policy': {
      id: '/_app/dashboard/policy'
      path: '/dashboard/policy'
      fullPath: '/dashboard/policy'
      preLoaderRoute: typeof AppDashboardPolicyRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/holdings': {
      id: '/_app/dashboard/holdings'
      path: '/dashboard/holdings'
      fullPath: '/dashboard/holdings'
      preLoaderRoute: typeof AppDashboardHoldingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/generate': {
      id: '/_app/dashboard/generate'
      path: '/dashboard/generate'
      fullPath: '/dashboard/generate'
      preLoaderRoute: typeof AppDashboardGenerateRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/components_lib': {
      id: '/_app/dashboard/components_lib'
      path: '/dashboard/components_lib'
      fullPath: '/dashboard/components_lib'
      preLoaderRoute: typeof AppDashboardComponents_libRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/audit': {
      id: '/_app/dashboard/audit'
      path: '/dashboard/audit'
      fullPath: '/dashboard/audit'
      preLoaderRoute: typeof AppDashboardAuditRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/users/': {
      id: '/_app/dashboard/users/'
      path: '/dashboard/users'
      fullPath: '/dashboard/users/'
      preLoaderRoute: typeof AppDashboardUsersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/settings/': {
      id: '/_app/dashboard/settings/'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof AppDashboardSettingsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/users/settings': {
      id: '/_app/dashboard/users/settings'
      path: '/dashboard/users/settings'
      fullPath: '/dashboard/users/settings'
      preLoaderRoute: typeof AppDashboardUsersSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppDashboardAuditRoute: typeof AppDashboardAuditRoute
  AppDashboardComponents_libRoute: typeof AppDashboardComponents_libRoute
  AppDashboardGenerateRoute: typeof AppDashboardGenerateRoute
  AppDashboardHoldingsRoute: typeof AppDashboardHoldingsRoute
  AppDashboardPolicyRoute: typeof AppDashboardPolicyRoute
  AppDashboardSuggestionsRoute: typeof AppDashboardSuggestionsRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppDashboardUsersSettingsRoute: typeof AppDashboardUsersSettingsRoute
  AppDashboardSettingsIndexRoute: typeof AppDashboardSettingsIndexRoute
  AppDashboardUsersIndexRoute: typeof AppDashboardUsersIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDashboardAuditRoute: AppDashboardAuditRoute,
  AppDashboardComponents_libRoute: AppDashboardComponents_libRoute,
  AppDashboardGenerateRoute: AppDashboardGenerateRoute,
  AppDashboardHoldingsRoute: AppDashboardHoldingsRoute,
  AppDashboardPolicyRoute: AppDashboardPolicyRoute,
  AppDashboardSuggestionsRoute: AppDashboardSuggestionsRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppDashboardUsersSettingsRoute: AppDashboardUsersSettingsRoute,
  AppDashboardSettingsIndexRoute: AppDashboardSettingsIndexRoute,
  AppDashboardUsersIndexRoute: AppDashboardUsersIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SandboxAuthRoute: SandboxAuthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiNexusAuthSplatRoute: ApiNexusAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
